In [2]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("naivebayes.csv")

In [6]:
from sklearn import preprocessing

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
from sklearn.naive_bayes import GaussianNB
# naive base theorem

In [9]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [10]:
df.isnull().sum()
df["Age"].mean()
new_Age=np.where(df["Age"].isnull(),29,df["Age"])
df["Age"]=new_Age

In [11]:
le=preprocessing.LabelEncoder()

In [12]:
df["Embarked"] = le.fit_transform(df["Embarked"].astype(str))

In [13]:
df["Sex"] = le.fit_transform(df["Sex"].astype(str))

In [14]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0       3    1  22.0      1      0   7.2500         2
1            2         1       1    0  38.0      1      0  71.2833         0
2            3         1       3    0  26.0      0      0   7.9250         2
3            4         1       1    0  35.0      1      0  53.1000         2
4            5         0       3    1  35.0      0      0   8.0500         2

In [18]:
y=df["Pclass"]

In [19]:
x=df.drop(["Pclass","PassengerId"],axis=1)

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
# as there is no condition is tere so random state is 0

In [21]:
from sklearn.naive_bayes import *

In [25]:
clf=GaussianNB()

In [26]:
y_pred=clf.fit(x_train,y_train).predict(x_test)

In [27]:
accuracy_score(y_test,y_pred,normalize=True)

0.7089552238805971

In [28]:
confusion_matrix(y_test,y_pred)

array([[ 42,  12,   6],
       [  3,  26,  23],
       [  7,  27, 122]], dtype=int64)

In [44]:
# pclass,gender,sibisp,parch,embarkerd

In [43]:
pd.array(['Pclass','Sex','SibSp','Parch','Embarked'], dtype="string")
for i in pd.array(['Pclass','Sex','SibSp','Parch','Embarked'], dtype="string"):
   y=df[i]
   x=df.drop([i,"PassengerId"],axis=1)
   x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
   y_pred=clf.fit(x_train,y_train).predict(x_test)
   print("Accuracy score of ",i,accuracy_score(y_test,y_pred,normalize=True),"\n")
   print("confusion matrix of",i,confusion_matrix(y_test,y_pred),"\n")

Accuracy score of  Pclass 0.7089552238805971 

confusion matrix of Pclass [[ 42  12   6]
 [  3  26  23]
 [  7  27 122]] 

Accuracy score of  Sex 0.7985074626865671 

confusion matrix of Sex [[ 71  28]
 [ 26 143]] 

Accuracy score of  SibSp 0.6455223880597015 

confusion matrix of SibSp [[158  10   0  13   0   0]
 [ 36   9   0  20   0   0]
 [  4   3   0   0   0   0]
 [  2   0   0   1   3   0]
 [  0   0   0   3   4   0]
 [  0   0   0   1   0   1]] 

Accuracy score of  Parch 0.7388059701492538 

confusion matrix of Parch [[180  13   2   9   0]
 [ 22  10   4   4   0]
 [  8   5   8   0   0]
 [  2   0   0   0   0]
 [  1   0   0   0   0]] 

Accuracy score of  Embarked 0.4962686567164179 

confusion matrix of Embarked [[22 20 18]
 [ 1 17  3]
 [12 81 94]] 



# we have used the for loop for finding out the accuracy score and the confusion matrix for pclass,Sex,sibisp,parch,embarkerd
- In that we could say accuracy score of "Sex" is greater than the rest 
- minimun accuracy score is "parch"